language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
before_install:
- npm install hexo-cli -g
install:
- npm install
script:
- hexo clean
- hexo generate
after_script:
  - cd ./public
  - git init
  - git config user.name "voodeng"
  - git config user.email "voodeng@gmail.com"
  - git add .
  - git commit -m "TravisCI Hexo Generate"
  # Github Pages
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master 

branches:
  only:
  - hexo-sourc

env:
 global:
   # Github Pages
   - GH_REF: github.com/voodeng/voodeng.github.com.git