language: node_js
node_js: stable

cache:
  directories:
  - node_modules

before_install:
- npm install hexo-cli -g
- git config --global user.name "voodeng"
- git config --global user.email "voodeng@gmail.com"

install:
- npm install

script:
- hexo clean
- hexo generate

after_success:
- git clone -b master "https://${GH_REF}" .deploy_git
- cd .deploy_git
- git checkout master
- mv .git/ ../public/
- cd ../public
- git add .
- git commit -m "Site updated: $(echo $(date +"%Y-%m-%d-%H:%M:%S"))"
- git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master 

branches:
  only:
  - hexo-source

env:
 global:
   # Github Pages
   - GH_REF: github.com/voodeng/voodeng.github.com.git